[package]
name = "SunCoin"
version = "0.0.0"

[addresses]
SunCoin = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir="aptos-move/framework/aptos-framework/", rev="aptos-cli-v0.3.4" }
